FROM	golang:1.14.3-buster AS krbuild
RUN	go get github.com/kryptco/kr ; echo 'ignore go install warning'
WORKDIR	/go/src/github.com/kryptco/kr
RUN	make all

FROM	golang:1.26-trixie

RUN	apt update && apt install -y \
		awscli \
		ca-certificates \
		curl \
		git \
		httpie \
		jq \
		less \
		locales \
		locales-all \
		man \
		python3 \
		python3-pip \
		python3-pynvim \
		rsync \
		silversearcher-ag \
		zip \
		zsh \
	&& rm -rf /var/lib/apt/lists/*

# copy krypton
COPY --from=krbuild /go/src/github.com/kryptco/kr/bin/ /usr/bin/

# set to swedish
ENV	LC_ALL=sv_SE.UTF-8
ENV	LANG=sv_SE.UTF-8
ENV	LANGUAGE=sv_SE.UTF-8

RUN	useradd -ms /bin/zsh dev
USER	dev
WORKDIR /home/dev

RUN	sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
COPY	--chown=dev ./devhome/ /home/dev/

#RUN	curl -fLo /home/dev/.local/share/nvim/site/autoload/plug.vim --create-dirs \
#		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

CMD	zsh
